version: '3.8'

services:
  # NestJS Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lms_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      APP_PORT: 3001
      APP_ENV: development
      FRONTEND_URL: https://mylms-jade.vercel.app
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_uploads:/app/uploads

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lms_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: https://mylms-jade.vercel.app/api
      NEXT_PUBLIC_MIDTRANS_CLIENT_KEY: ${MIDTRANS_CLIENT_KEY:-}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  backend_uploads:
